set_property SRC_FILE_INFO {cfile:C:/Users/ethan/Documents/pynq/nexys_pwm/Nexys-A7-100T-Master.xdc rfile:../../../Nexys-A7-100T-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F16 [get_ports pwm0_0]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D14 [get_ports {gpio_io_o_0[0]}]
